### ISSUE TITLE
Migration from gitlab to gigs/gitea

### ISSUE THREAD

**Issue by cpetry** [ronnyhartenstein/ronnyhartenstein.github.io#2]
Hello there!

First of all thanks for this detailed description of the migration possibilities.
One question though: are issues also migrated over to gigs?
I have a project with >300 closed and 150 open issues that I do not want to create manually.

Thank you!

**Comment by ronnyhartenstein** [comment]
Well, I don't know how to migration issues. But you can google for "migrate gitlab to gogs" and you'll find a Python script and some blogpost. Sorry, I can't help you in detail.
